### ISSUE TITLE
Custom fields returning 'has no value'

### ISSUE THREAD

**Issue by hsystems7** [Lerentis/bitwarden-crd-operator#23]
Hey there,
with your newest version 0.6.0 there might be a bug.
Trying to read a custom field from my bitwarden. SecretScope is set to `fields`. Tested it numerous times. The only scope which is working is the `login` scope.
Even tested it manually with the Bitwarden CLI to check, if there is anything there. There is.
Downgraded to 0.5.4 and have no problems, even with custom fields.
Might have to do with your recent changes to `utils.py` in `parse_fields_scope`.  :)
Let me know if you need any more information.

**Comment by Lerentis** [comment]
Hi @hsystems7 ,

Thanks for the report. I am currently moving and hope to get a working internet connection by end of next week. I will take a closer look by then.
In the mean time I hope that you can stay with the previous release and upgrade as soon as this gets fixed

**Comment by Lerentis** [comment]
Fixed with https://github.com/Lerentis/bitwarden-crd-operator/commit/886fe3783d91bdb725f610528080b80af58e3f40 and released with https://github.com/Lerentis/bitwarden-crd-operator/releases/tag/bitwarden-crd-operator-v0.7.1 :)

Thanks again for the report!
