### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by mbathe19** [Lerentis/bitwarden-crd-operator#25]
Hi, I installed the operator like you wrote in the docs, but im getting the following error:

` {"message": "Activity 'bitwarden_signin' failed with an exception. Will retry.", "exc_info": "Traceback (most recent call last):\n File \"/usr/lib/python3.10/site-packages/kopf/_core/actions/execution.py\", line 279, in execute_handler_once\n result = await invoke_handler(\n File \"/usr/lib/python3.10/site-packages/kopf/_core/actions/execution.py\", line 374, in invoke_handler\n result = await invocation.invoke(\n File \"/usr/lib/python3.10/site-packages/kopf/_core/actions/invocation.py\", line 139, in invoke\n await asyncio.shield(future) # slightly expensive: creates tasks\n File \"/usr/lib/python3.10/concurrent/futures/thread.py\", line 58, in run\n result = self.fn(*self.args, **self.kwargs)\n File \"/home/bw-operator/bitwardenCrdOperator.py\", line 19, in bitwarden_signin\n command_wrapper(logger, \"login --apikey\")\n File \"/home/bw-operator/utils/utils.py\", line 35, in command_wrapper\n resp = json.loads(out.decode(encoding='UTF-8'))\n File \"/usr/lib/python3.10/json/__init__.py\", line 346, in loads\n return _default_decoder.decode(s)\n File \"/usr/lib/python3.10/json/decoder.py\", line 337, in decode\n obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n File \"/usr/lib/python3.10/json/decoder.py\", line 355, in raw_decode\n raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)", "timestamp": "2023-05-09T00:30:55.035056+00:00", "severity": "error"}`

Any idea how to fix it? Do you need more informations?

**Comment by Lerentis** [comment]
Hi @mbathe19 ,

From a first guess I would say the credential you provided are wrong. Do you use an external secret for the deployment or pass the environment variables explicitly?
Also you can try to downgrade to the previous version. There was a rework of the command wrapper logic

**Comment by mbathe19** [comment]
Hi,

thanks for the fast response.
I used both external and env vars. And if i use bw login --apikey my credentials work. I need to say i use vaultwarden and not bitwarden itself. Is it a problem or should it work too?

Also i downgraded the version. New error:
`{"message": "Activity 'bitwarden_signin' failed with an exception. Will retry.", "exc_info": "Traceback (most recent call last):\n File \"/usr/lib/python3.10/site-packages/kopf/_core/actions/execution.py\", line 279, in execute_handler_once\n result = await invoke_handler(\n File \"/usr/lib/python3.10/site-packages/kopf/_core/actions/execution.py\", line 374, in invoke_handler\n result = await invocation.invoke(\n File \"/usr/lib/python3.10/site-packages/kopf/_core/actions/invocation.py\", line 139, in invoke\n await asyncio.shield(future) # slightly expensive: creates tasks\n File \"/usr/lib/python3.10/concurrent/futures/thread.py\", line 58, in run\n result = self.fn(*self.args, **self.kwargs)\n File \"/home/bw-operator/bitwardenCrdOperator.py\", line 19, in bitwarden_signin\n command_wrapper(\"login --apikey\")\n File \"/home/bw-operator/utils/utils.py\", line 37, in command_wrapper\n raise BitwardenCommandException(err)\nutils.utils.BitwardenCommandException: b\"/usr/local/bin/bw: line 1: can't create \\x01\\xf3\\xbd\\x8e@\\xf8\\xa0\\x89\\x02@8\\r@\\x1f\\x1e\\x06\\x04@@@@@\\xd8\\x02\\xd8\\x02\\x08\\x03\\x04\\x18\\x03\\x18\\x03@\\x18\\x03@\\x1c\\x1c\\x01\\x01\\x04@@\\x10\\x08L\\x10\\x08L\\x10\\x01\\x05\\x10L\\x10\\x8c\\x10\\x8c\\x1a\\xb5H\\x01\\x1a\\xb5H\\x01\\x10\\x01\\x05\\xd0\\x94\\x01\\xe0\\x01\\xe0\\x01\\xa9\\x01\\xa9\\x01\\x10\\x01\\x04\\xe0\\x94\\x01\\x10\\xe0\\x01\\x10\\xe0\\x01\\xae: Permission denied\\n/usr/local/bin/bw: line 2: syntax error: unterminated quoted string\\n\"", "timestamp": "2023-05-09T21:59:00.163740+00:00", "severity": "error"}`

Than i tried the execution shell at the pod with `bw` and got (at version 0.6.0 and 0.7.0) :
```
@@@@@@�@@@LL���H�HД���������: Permission denied@8
/usr/local/bin/bw: line 2: syntax error: unterminated quoted string
```
Do you have more suggestions to try out?

Thanks for your time! Kind regards

Michel

**Comment by Lerentis** [comment]
On what system do you deploy (cpu architecture/OS) and what is the image that you run? the syntax error when just executing the bitwarden cli seems like either a unsupported architecture or a corrupt image.

**Comment by mbathe19** [comment]
I am runnig it on an raspberrypi cluster. 
So cpui is:
```
Architecture:                    aarch64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
CPU(s):                          4
On-line CPU(s) list:             0-3
Thread(s) per core:              1
Core(s) per socket:              4
Socket(s):                       1
Vendor ID:                       ARM
Model:                           3
Model name:                      Cortex-A72
Stepping:                        r0p3
CPU max MHz:                     1500.0000
CPU min MHz:                     600.0000
BogoMIPS:                        108.00
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Vulnerable
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fp asimd evtstrm crc32 cpuid
```

And OS is:
```
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

So should i build the container my self on an raspi?

Regards

**Comment by Lerentis** [comment]
@mbathe19 can you build the image locally from the linked pull request and confirm if this approach is working or now? i currently don't have an arm cluster at hand to test but i am rather confident that this should work

**Comment by mbathe19** [comment]
@Lerentis ok i have some results for you.
The image was succesfully build and is running fine. (Built it with dockerx and on a pi)
I finally see some succesfull login attempts on vaultwarden.
But the container is not staying up:

```
{"message": "Rate limit exceeded. Try again later.", "success": false, "timestamp": "2023-05-11T12:05:51.386414+00:00", "severity": "warn"}
3
{"message": "Signal SIGTERM is received. Operator is stopping.", "timestamp": "2023-05-11T12:06:01.955362+00:00", "severity": "info"}
2
{"message": "You are not logged in.", "success": false, "timestamp": "2023-05-11T12:06:05.030155+00:00", "severity": "warn"}
1
{"message": "Activity 'bitwarden_signin' failed with an exception. Will retry.", "exc_info": "Traceback (most recent call last):\n  File \"/usr/lib/python3.10/site-packages/kopf/_core/actions/execution.py\", line 276, in execute_handler_once\n    result = await invoke_handler(\n  File \"/usr/lib/python3.10/site-packages/kopf/_core/actions/execution.py\", line 371, in invoke_handler\n    result = await invocation.invoke(\n  File \"/usr/lib/python3.10/site-packages/kopf/_core/actions/invocation.py\", line 139, in invoke\n    await asyncio.shield(future)  # slightly expensive: creates tasks\n  File \"/usr/lib/python3.10/concurrent/futures/thread.py\", line 58, in run\n    result = self.fn(*self.args, **self.kwargs)\n  File \"/home/bw-operator/bitwardenCrdOperator.py\", line 20, in bitwarden_signin\n    unlock_bw(logger)\n  File \"/home/bw-operator/utils/utils.py\", line 21, in unlock_bw\n    os.environ[\"BW_SESSION\"] = token_output[\"data\"][\"raw\"]\nTypeError: 'NoneType' object is not subscriptable", "timestamp": "2023-05-11T12:06:05.031568+00:00", "severity": "error"}
```

Maybe it is the Readniss or Liveness Probe? Maybe there is a way to increase the time from 5 Seconds to 10 or more?
Maybe you have some hints?

Thanks again for the fix,

Michel

**Comment by Lerentis** [comment]
>`token_output[\"data\"][\"raw\"]\nTypeError: 'NoneType' object is not subscriptable"`

this seems more like a wrong password now. as you may have seen already the operator wraps around the bitwarden cli. in the call `bw --response unlock` has two json objects that it can respond with (bad design imo but this part is out of my reach):

```json
{
  "success": true,
  "data": {
    "noColor": false,
    "object": "message",
    "title": "Your vault is now unlocked!",
    "message": "\nTo unlock your vault, set your session key to the `BW_SESSION` environment variable. ex:\n$ export BW_SESSION=\"REDACTED\"\n> $env:BW_SESSION=\"REDACTED"\n\nYou can also pass the session key to any command with the `--session` option. ex:\n$ bw list items --session REDACTED",
    "raw": "REDACTED"
  }
}
```

or

```json
{"success":false,"message":"Invalid master password."}
```

if `success: false` the command wrapper returns `None` and logs the response. in the logs you have send above there is a statement about `Rate limit exceeded` so i guess there are some bad logins before this one

**Comment by Lerentis** [comment]
@mbathe19 feel free to reopen if the error persists

**Comment by mbathe19** [comment]
Hey @Lerentis,

I finally got some time and got it working. 
The problem was like I mentioned the readiness and liveness probe.
For a "slow" cluster like mine, the probes timelimt aren't working. I always got the mail that someone logged in, so I knew credentials are working.
What worked for me is:

```
ports:
  - name: http
    containerPort: 8080
    protocol: TCP
livenessProbe:
  httpGet:
    path: /healthz
    port: http
  periodSeconds: 30
  initialDelaySeconds: 30
readinessProbe:
  httpGet:
    path: /healthz
    port: http
  periodSeconds: 30
  initialDelaySeconds: 30
```

Nice would be is a section in the values file where you can tweak these probes. If you want, I can create a pull request.
Regards,

Michel

**Comment by Lerentis** [comment]
Hi @mbathe19 ,

thanks for the feedback. indeed the chart is lacking these configuration possibilities at the moment. as my son is demanding the majority of my free time at the moment, a PR would be highly appreciated 😅
