### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by mbathe19** [Lerentis/bitwarden-crd-operator#46]
Hi,

finally got the operaotpr working, but now i have the problem that i cant get secrets working:
I get the folloiwng error message:

`Handler 'create_managed_secret' failed with an exception. Will retry. Traceback (most recent call last): File "/usr/lib/python3.10/site-packages/kopf/_core/actions/execution.py", line 276, in execute_handler_once result = await invoke_handler( File "/usr/lib/python3.10/site-packages/kopf/_core/actions/execution.py", line 371, in invoke_handler result = await invocation.invoke( File "/usr/lib/python3.10/site-packages/kopf/_core/actions/invocation.py", line 139, in invoke await asyncio.shie....10/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) File "/home/bw-operator/kv.py", line 59, in create_managed_secret secret = create_kv(secret, secret_json_object, content_def) File "/home/bw-operator/kv.py", line 22, in create_kv value = parse_login_scope(secret_json, _secret_key) File "/home/bw-operator/utils/utils.py", line 45, in parse_login_scope return secret_json["data"]["login"][key] TypeError: 'NoneType' object is not subscriptable`

My bitwarden.yaml
![image](https://github.com/Lerentis/bitwarden-crd-operator/assets/56388966/e97f046c-bd5e-4ed3-8a7d-da6a030b1931)

The secret from bw-cli:
![image](https://github.com/Lerentis/bitwarden-crd-operator/assets/56388966/8221b70f-c50d-4476-a637-483580963892)

The complete error:
![image](https://github.com/Lerentis/bitwarden-crd-operator/assets/56388966/73367ece-f403-4aee-b8d2-356a830a9456)

Any idea or hint why its not wortking?

Have a nice day,

Michel

**Comment by Lerentis** [comment]
Hi @mbathe19 ,
thanks for including the whole log entry. i would recommend that you double check the permissions of the user that is deployed with the operator and the ID of the secret that you are trying to get via the operator. the bw cli reports "Not Found" as well if the current user does not have access to the requested entry in order to not leak information about valid IDs. i think this may be rather an access denied.
If you need more information from the logs you can specify an additional env `DEBUG=true` to get more verbose logs. please be aware that this will also leak secrets to the logs

**Comment by mbathe19** [comment]
Hi,

activated with DEBUG=true, the restart was enough to get it working. Maybe it needs some bounce her and then.
So its working now, as always thany you. Regards Michel

**Comment by mbathe19** [comment]
Hi @Lerentis,

found the Problem, the problem is: 
If you create a session and add then a password in vaultwarden web ui, the password can't be found. 
If you redeploy the pod, the password is now available. I think it syncs again?!?

A sync job every 5 to 10 minutes making a bw sync would be awesome. Any idea how to implement it?

Regards,
Michel

**Comment by Lerentis** [comment]
@mbathe19 this was implemented and released yesterday (:

You can define a sync interval with the env BW_SYNC_INTERVAL
Per default it is 900 seconds

**Comment by Lerentis** [comment]
There is also the env BW_FORCE_SYNC to force a bw sync with every lookup operation

**Comment by mbathe19** [comment]
Hi @Lerentis,

that's pretty neat,I am implementing it atm.
Will close the ticket for now, problem is solved. 
FYI: Building it, I needed to modify the the Python Version to `PYTHON_VERSION=3.11.6-r0` otherwise the python version isn't found.

Thanks a lot regards,
Michel

**Comment by Lerentis** [comment]
What is stopping you from using the upstream image?

**Comment by mbathe19** [comment]
Nothing, just stuck to the selfbuild image, back when we tested arm for the first time.
Updated to the upstream, so i can better test :)
All working smooth now.
