### ISSUE TITLE
"You are not logged in"

### ISSUE THREAD

**Issue by mbathe19** [Lerentis/bitwarden-crd-operator#47]
Hi,

have the problem that from time to time the operator pod gets logged out. (not sure about the time now)
I got the follwing error:
`You are not logged in` and the password lookup fails.

The vaultwarden server isn't restarted, same as the operator. If I restart the operator he is back logged in and working.
Any idea to fix the problem?

Regards,

Michel

**Comment by mbathe19** [comment]
Maybe i solved the problem by my self.
After some digging, i noticed that the proxy cuts connection from time to time.  
So used the internal k8s-svc of my vaultwarden container as 'BW_HOST' -env. 
I will report if it fixed my problem.

**Comment by mbathe19** [comment]
Unfortunately this didn't solved the problem. Do have any idea?

**Comment by Lerentis** [comment]
Hmm the docs are a little unspecified here. From an old forum entry I read that sessions never expire but this may have changed or is different in vaultwarden. The fix in the end would be to call the login function again before the session is expired. Do you have any time estimation when this happens?

**Comment by mbathe19** [comment]
Yea, was also searching for it, but also found nothing.
No at the moment not. Unfortunately i always miss the timespot where it switches from logged in to you are not logged in.
Maybe an env would be nice, to figure out the best time. 
For example start 3600 seconds, if it works go to 7200 seconds and so on.

**Comment by Lerentis** [comment]
Try again with the latest release. i added a configurable schedule so you can trigger a relogin whenever you please that defaults to every 30 minutes

**Comment by mbathe19** [comment]
Hi, already deploying it.
Thanks man!
