### ISSUE TITLE
Custom  Annotations

### ISSUE THREAD

**Issue by chrthal** [Lerentis/bitwarden-crd-operator#81]
Hi,
is it possible to extend the template of the secret to add additional custom annotations?

**Comment by Lerentis** [comment]
Hey there,
i dont think i support custom annotations yet, just labels. But i'll look into it. maybe this can be a quick win

**Comment by Lerentis** [comment]
reasonable quick win. annotations are now merged with the default once, so you can define what you need @chrthal

**Comment by chrthal** [comment]
Thank you!
For upgrading the api version - registry credentials must be recreated. Schema merging does not seem to work.
After recreation the custom annotations are working perfectly!
