### ISSUE TITLE
TLS credential creation

### ISSUE THREAD

**Issue by chrthal** [Lerentis/bitwarden-crd-operator#83]
Can we add the functionality to create secrets with type kubernetes.io/tls?

**Comment by Lerentis** [comment]
Hi @chrthal
Intersting idea. I am not sure how that would look in the end as the pki would need to resign in one bitwarden entry... Probably cert manager would be the better tool for this feature?

**Comment by chrthal** [comment]
Hi @Lerentis 
I think there are two ways of making that possible. The first and probably easiest way would be just making the type of the BitwardenTemplate modifiable since attachments are already implemented in there. The second approach would be creating a dedicated type for TLS Entries with assuming that certs are always provided as attachments.

**Comment by Lerentis** [comment]
finally had some time to fix the release pipeline. your changes have been shipped with https://github.com/Lerentis/bitwarden-crd-operator/releases/tag/bitwarden-crd-operator-v0.13.0 . Thanks again for raising and implementing this
